#!/bin/sh
set -e

# Define variables to substitute
export DOLLAR='$'
# shellcheck disable=SC2016
envsubst '${UPSTREAM_WEB_HOST} ${UPSTREAM_WEB_PORT} ${UPSTREAM_API_HOST} ${UPSTREAM_API_PORT} ${UPSTREAM_GRAFANA_HOST} ${UPSTREAM_GRAFANA_PORT} ${UPSTREAM_PROMETHEUS_HOST} ${UPSTREAM_PROMETHEUS_PORT} ${UPSTREAM_LOKI_HOST} ${UPSTREAM_LOKI_PORT} ${UPSTREAM_TEMPO_HOST} ${UPSTREAM_TEMPO_PORT} ${UPSTREAM_MINIO_CONSOLE_HOST} ${UPSTREAM_MINIO_CONSOLE_PORT} ${UPSTREAM_MINIO_S3_HOST} ${UPSTREAM_MINIO_S3_PORT} ${UPSTREAM_BEACON_LIBRARY_HOST} ${UPSTREAM_BEACON_LIBRARY_PORT} ${MAX_BODY_SIZE} ${GZIP_ENABLED} ${DOLLAR}' \
  < /etc/nginx/nginx.conf.template \
  > /etc/nginx/nginx.conf

exec "$@"
